project_id = "baiiznjzvzhxwwqzsozn"

[functions.get-zoom-recording]
verify_jwt = false

[functions.analyze-roleplay]
verify_jwt = false

[functions.post-roleplay-to-slack]
verify_jwt = false

[functions.notify-ranking]
verify_jwt = false

[functions.proxy-drive-download]
verify_jwt = false

[functions.sync-zoom-users]
verify_jwt = false

[functions.migrate-auth-to-email]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.receive-zoom-webhook]
verify_jwt = false

[functions.notify-team-report]
verify_jwt = false

[functions.upload-to-gdrive]
verify_jwt = false

[functions.invite-member]
verify_jwt = false
