-- 買収タブ：同じ日に入れた段階の順番を保つため、段階の履歴に通し番号を足す。
-- 現在の段階は「日付の新しい順 → 通し番号の大きい順」の先頭（acq_deal_list）。
set lock_timeout = '5s';
alter table public.acq_deal_stage_events add column if not exists seq bigint generated by default as identity;
create or replace view public.acq_deal_list
with (security_invoker = true) as
select
  d.*,
  coalesce(d.name, d.project_name) as display_name,
  st.stage as current_stage,
  st.occurred_on as stage_on,
  sf.name as source_firm_name,
  sc.name as source_contact_name,
  ss.name as sell_side_firm_name,
  fin_ours.ebitda as ebitda_ours,
  fin_im.ebitda as ebitda_im,
  coalesce(fin_ours.revenue, fin_im.revenue) as revenue,
  coalesce(fin_ours.net_cash, fin_im.net_cash) as net_cash,
  case
    when coalesce(fin_ours.ebitda, fin_im.ebitda) > 0 and coalesce(d.asking_price_min, d.asking_price_max) is not null
    then round(((coalesce(d.asking_price_min, d.asking_price_max) + coalesce(d.asking_price_max, d.asking_price_min)) / 2.0)
               / coalesce(fin_ours.ebitda, fin_im.ebitda), 1)
  end as multiple,
  docs.has_nonname, docs.has_im, docs.has_qa, docs.doc_count,
  act.last_activity_at
from public.acq_deals d
left join lateral (
  select e.stage, e.occurred_on from public.acq_deal_stage_events e
   where e.deal_id = d.id order by e.occurred_on desc, e.seq desc limit 1
) st on true
left join public.acq_firms sf on sf.id = d.source_firm_id
left join public.acq_contacts sc on sc.id = d.source_contact_id
left join public.acq_firms ss on ss.id = d.sell_side_firm_id
left join lateral (
  select f.* from public.acq_deal_financials f where f.deal_id = d.id and f.source = 'ours'
   order by f.period_end desc nulls last, f.created_at desc limit 1
) fin_ours on true
left join lateral (
  select f.* from public.acq_deal_financials f where f.deal_id = d.id and f.source = 'im'
   order by f.period_end desc nulls last, f.created_at desc limit 1
) fin_im on true
left join lateral (
  select bool_or(x.doc_type = 'nonname') as has_nonname,
         bool_or(x.doc_type = 'im') as has_im,
         bool_or(x.doc_type = 'qa') as has_qa,
         count(*) as doc_count
    from public.acq_documents x where x.deal_id = d.id
) docs on true
left join lateral (
  select max(a.occurred_at) as last_activity_at
    from public.acq_activity_deals ad join public.acq_activities a on a.id = ad.activity_id
   where ad.deal_id = d.id
) act on true;
